name = "problem56"
version = "0.1.0"
defaultTargets = ["Solution", "Challenge"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "Problem56"
srcDir = "research/problem_5_6/formalization/lean"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
