import Problem56.CumulantMoment

/-!
Finite combinatorics for the product-cumulant identity in I09.
-/

open scoped BigOperators

namespace Problem56

private noncomputable def stirlingMobiusRangeSum (b : ℕ) : ℤ :=
  ∑ k ∈ Finset.range b,
    (Nat.stirlingSecond b (k + 1) : ℤ) * (-1 : ℤ) ^ k *
      (Nat.factorial k : ℤ)

private theorem stirlingMobiusRangeSum_succ_succ (n : ℕ) :
    stirlingMobiusRangeSum (n + 2) = 0 := by
  let N := n + 1
  let F : ℕ → ℤ := fun k ↦
    (Nat.stirlingSecond N (k + 1) : ℤ) * (-1 : ℤ) ^ k *
      (Nat.factorial k : ℤ)
  let A : ℕ → ℤ := fun k ↦ (k + 1 : ℕ) * F k
  let B : ℕ → ℤ := fun k ↦
    (Nat.stirlingSecond N k : ℤ) * (-1 : ℤ) ^ k *
      (Nat.factorial k : ℤ)
  have hexpand : stirlingMobiusRangeSum (n + 2) =
      (∑ k ∈ Finset.range (N + 1), A k) +
        ∑ k ∈ Finset.range (N + 1), B k := by
    rw [stirlingMobiusRangeSum]
    have hn2 : n + 2 = N + 1 := by simp [N]
    rw [hn2]
    calc
      _ = ∑ k ∈ Finset.range (N + 1), (A k + B k) := by
        apply Finset.sum_congr rfl
        intro k _
        rw [Nat.stirlingSecond_succ_succ]
        simp only [A, B, F, Nat.cast_add, Nat.cast_mul]
        ring
      _ = _ := Finset.sum_add_distrib
  rw [hexpand]
  have hA : (∑ k ∈ Finset.range (N + 1), A k) =
      ∑ k ∈ Finset.range N, A k := by
    rw [Finset.sum_range_succ]
    have hzero : Nat.stirlingSecond N (N + 1) = 0 :=
      Nat.stirlingSecond_eq_zero_of_lt (Nat.lt_succ_self N)
    simp [A, F, hzero]
  have hB : (∑ k ∈ Finset.range (N + 1), B k) =
      ∑ k ∈ Finset.range N, B (k + 1) := by
    rw [Finset.sum_range_succ']
    have hNpos : 0 < N := by simp [N]
    obtain ⟨m, hm⟩ := Nat.exists_eq_succ_of_ne_zero hNpos.ne'
    have hzero : Nat.stirlingSecond N 0 = 0 := by
      rw [hm, Nat.stirlingSecond_succ_zero]
    simp [B, hzero]
  rw [hA, hB, ← Finset.sum_add_distrib]
  apply Finset.sum_eq_zero
  intro k hk
  simp only [A, B, F]
  rw [Nat.factorial_succ, pow_succ, Nat.cast_mul, Nat.cast_add,
    Nat.cast_one]
  ring

private theorem stirlingMobiusIcc_eq_range (b : ℕ) :
    (∑ j ∈ Finset.Icc 1 b,
      (Nat.stirlingSecond b j : ℤ) * (-1 : ℤ) ^ (j - 1) *
        (Nat.factorial (j - 1) : ℤ)) = stirlingMobiusRangeSum b := by
  classical
  have hset : Finset.Icc 1 b =
      (Finset.range b).image (fun k ↦ k + 1) := by
    ext j
    simp only [Finset.mem_Icc, Finset.mem_image, Finset.mem_range]
    constructor
    · rintro ⟨hj1, hjb⟩
      refine ⟨j - 1, by omega, by omega⟩
    · rintro ⟨k, hkb, rfl⟩
      omega
  rw [hset, Finset.sum_image]
  · simp [stirlingMobiusRangeSum]
  · intro k _ l _ hkl
    exact Nat.add_right_cancel hkl

/-- The explicit Stirling coefficient in I09. -/
theorem stirling_product_cumulant_coefficient (b : ℕ) :
    (∑ j ∈ Finset.Icc 1 b,
      (Nat.stirlingSecond b j : ℤ) * (-1 : ℤ) ^ (j - 1) *
        (Nat.factorial (j - 1) : ℤ)) =
      if b = 1 then 1 else 0 := by
  rw [stirlingMobiusIcc_eq_range]
  cases b with
  | zero => simp [stirlingMobiusRangeSum]
  | succ n =>
      cases n with
      | zero => norm_num [stirlingMobiusRangeSum, Nat.stirlingSecond]
      | succ n =>
          rw [if_neg (by omega)]
          simpa only [Nat.succ_eq_add_one, Nat.add_assoc,
            Nat.reduceAdd] using stirlingMobiusRangeSum_succ_succ n

/-! ### Connectivity partition generated by two partitions -/

private def productPartitionStep
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) (i j : ι) : Prop :=
  σ.part i = σ.part j ∨ τ.part i = τ.part j

private theorem productPartitionStep_symm
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) {i j : ι}
    (h : productPartitionStep σ τ i j) :
    productPartitionStep σ τ j i := by
  rcases h with h | h
  · exact Or.inl h.symm
  · exact Or.inr h.symm

noncomputable def productConnectivitySetoid
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) : Setoid ι where
  r := Relation.ReflTransGen (productPartitionStep σ τ)
  iseqv := by
    constructor
    · intro i
      exact Relation.ReflTransGen.refl
    · intro i j h
      exact Relation.ReflTransGen.mono
        (r := Function.swap (productPartitionStep σ τ))
        (p := productPartitionStep σ τ)
        (fun _ _ hstep ↦ productPartitionStep_symm σ τ hstep) j i h.swap
    · intro i j k hij hjk
      exact hij.trans hjk

noncomputable def productConnectivityPartition
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    Finpartition (Finset.univ : Finset ι) := by
  classical
  exact Finpartition.ofSetoid (productConnectivitySetoid σ τ)

@[simp]
theorem mem_productConnectivityPartition_part_iff
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) (i j : ι) :
    j ∈ (productConnectivityPartition σ τ).part i ↔
      Relation.ReflTransGen
        (fun a b ↦ σ.part a = σ.part b ∨ τ.part a = τ.part b) i j := by
  classical
  exact Finpartition.mem_part_ofSetoid_iff_rel

theorem productPartitionConnected_iff_connectivity_card_one
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    ProductPartitionConnected σ τ ↔
      (productConnectivityPartition σ τ).parts.card = 1 := by
  classical
  let K := productConnectivityPartition σ τ
  constructor
  · intro hconn
    have hK : K = Finpartition.indiscrete Finset.univ_nonempty.ne_empty := by
      apply finpartition_eq_indiscrete_of_card_parts_eq_one
        Finset.univ_nonempty.ne_empty K
      apply Finset.card_eq_one.mpr
      refine ⟨Finset.univ, ?_⟩
      apply Finset.eq_singleton_iff_nonempty_unique_mem.mpr
      constructor
      · exact K.parts_nonempty Finset.univ_nonempty.ne_empty
      · intro B hB
        apply Finset.Subset.antisymm (K.subset hB)
        intro j _
        obtain ⟨i, hiB⟩ := K.nonempty_of_mem_parts hB
        have hij : Relation.ReflTransGen
            (fun a b ↦ σ.part a = σ.part b ∨ τ.part a = τ.part b) i j :=
          hconn i j
        have hjpart : j ∈ K.part i :=
          (mem_productConnectivityPartition_part_iff σ τ i j).mpr hij
        have hpartB : K.part i = B :=
          K.part_eq_of_mem hB hiB
        simpa only [hpartB] using hjpart
    change K.parts.card = 1
    rw [hK, Finpartition.indiscrete_parts Finset.univ_nonempty.ne_empty]
    simp
  · intro hcard i j
    have hK := finpartition_eq_indiscrete_of_card_parts_eq_one
      Finset.univ_nonempty.ne_empty K hcard
    have hj : j ∈ K.part i := by
      rw [hK]
      let Ptop : Finpartition (Finset.univ : Finset ι) :=
        Finpartition.indiscrete Finset.univ_nonempty.ne_empty
      have hparts : Ptop.parts = {Finset.univ} :=
        Finpartition.indiscrete_parts Finset.univ_nonempty.ne_empty
      have huniv : (Finset.univ : Finset ι) ∈ Ptop.parts := by
        rw [hparts]
        exact Finset.mem_singleton_self _
      have hpart : Ptop.part i = Finset.univ :=
        Ptop.part_eq_of_mem huniv (Finset.mem_univ i)
      change j ∈ Ptop.part i
      rw [hpart]
      exact Finset.mem_univ j
    exact (mem_productConnectivityPartition_part_iff σ τ i j).mp hj

/-! ### Reindexing cumulants along finite equivalences -/

private noncomputable def finsetOrderIsoOfEquiv
    {α β : Type*} [DecidableEq α] [DecidableEq β]
    (e : α ≃ β) : Finset α ≃o Finset β where
  toEquiv := e.finsetCongr
  map_rel_iff' := by
    intro s t
    simp only [Equiv.finsetCongr_apply]
    exact Finset.map_subset_map

@[simp]
private theorem finsetOrderIsoOfEquiv_apply
    {α β : Type*} [DecidableEq α] [DecidableEq β]
    (e : α ≃ β) (s : Finset α) :
    finsetOrderIsoOfEquiv e s = s.map e.toEmbedding :=
  rfl

private noncomputable def finpartitionMapEquiv
    {α β : Type*} [Lattice α] [OrderBot α]
    [Lattice β] [OrderBot β]
    (e : α ≃o β) (a : α) :
    Finpartition a ≃ Finpartition (e a) where
  toFun P := P.map e
  invFun Q := (Q.map e.symm).copy (e.symm_apply_apply a)
  left_inv P := by
    apply Finpartition.ext
    simp only [Finpartition.copy_parts, Finpartition.parts_map]
    ext A
    simp only [Finset.mem_map]
    constructor
    · rintro ⟨B, ⟨C, hC, hCB⟩, hBA⟩
      have hCA : C = A := by
        rw [← hBA, ← hCB]
        exact (e.symm_apply_apply C).symm
      exact hCA ▸ hC
    · intro hA
      refine ⟨e A, ⟨A, hA, rfl⟩, e.symm_apply_apply A⟩
  right_inv Q := by
    apply Finpartition.ext
    simp only [Finpartition.parts_map, Finpartition.copy_parts]
    ext B
    simp only [Finset.mem_map]
    constructor
    · rintro ⟨A, ⟨C, hC, hCA⟩, hAB⟩
      have hCB : C = B := by
        rw [← hAB, ← hCA]
        exact (e.apply_symm_apply C).symm
      exact hCB ▸ hC
    · intro hB
      refine ⟨e.symm B, ⟨B, hB, rfl⟩, e.apply_symm_apply B⟩

private noncomputable def finpartitionCopyEquiv
    {α : Type*} [Lattice α] [OrderBot α] {a b : α} (h : a = b) :
    Finpartition a ≃ Finpartition b where
  toFun P := P.copy h
  invFun Q := Q.copy h.symm
  left_inv P := by subst b; rfl
  right_inv Q := by subst b; rfl

@[simp]
private theorem finsetOrderIsoOfEquiv_univ
    {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β] (e : α ≃ β) :
    finsetOrderIsoOfEquiv e (Finset.univ : Finset α) = Finset.univ := by
  ext y
  simp

private noncomputable def finpartitionCongr
    {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β] (e : α ≃ β) :
    Finpartition (Finset.univ : Finset α) ≃
      Finpartition (Finset.univ : Finset β) :=
  (finpartitionMapEquiv (finsetOrderIsoOfEquiv e) Finset.univ).trans
    (finpartitionCopyEquiv (finsetOrderIsoOfEquiv_univ e))

@[simp]
private theorem finpartitionCongr_parts
    {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β] (e : α ≃ β)
    (P : Finpartition (Finset.univ : Finset α)) :
    (finpartitionCongr e P).parts =
      P.parts.map (finsetOrderIsoOfEquiv e).toEmbedding :=
  rfl

private theorem jointCumulantOn_equiv
    {Ω α β : Type*} [Fintype Ω] [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    (e : α ≃ β) (Y : β → Ω → ℝ) :
    jointCumulantOn (fun a ↦ Y (e a)) = jointCumulantOn Y := by
  classical
  rw [jointCumulantOn, jointCumulantOn]
  apply Fintype.sum_equiv (finpartitionCongr e)
  intro P
  have hcard : (finpartitionCongr e P).parts.card = P.parts.card := by
    rw [finpartitionCongr_parts, Finset.card_map]
  rw [hcard]
  congr 1
  rw [finpartitionCongr_parts, Finset.prod_map]
  apply Finset.prod_congr rfl
  intro A _
  apply congrArg uniformExpectation
  funext ω
  change (∏ j ∈ A, Y (e j) ω) =
    ∏ j ∈ A.map e.toEmbedding, Y j ω
  rw [Finset.prod_map]
  rfl

private noncomputable def mappedBlockElementEquiv
    {ι : Type*} [DecidableEq ι] (B : Finset ι) (C : Finset B) :
    C ≃ (C.map
      (⟨Subtype.val, Subtype.val_injective⟩ : B ↪ ι)) where
  toFun j := ⟨j.1.1, Finset.mem_map.mpr ⟨j.1, j.2, rfl⟩⟩
  invFun j :=
    let h := Finset.mem_map.mp j.2
    ⟨Classical.choose h, (Classical.choose_spec h).1⟩
  left_inv j := by
    apply Subtype.ext
    let h := Finset.mem_map.mp
      (show j.1.1 ∈ C.map
        (⟨Subtype.val, Subtype.val_injective⟩ : B ↪ ι) from
          Finset.mem_map.mpr ⟨j.1, j.2, rfl⟩)
    apply Subtype.ext
    exact (Classical.choose_spec h).2
  right_inv j := by
    apply Subtype.ext
    let h := Finset.mem_map.mp j.2
    exact (Classical.choose_spec h).2

private theorem jointCumulantOn_mappedBlock
    {Ω ι : Type*} [Fintype Ω] [DecidableEq ι]
    (Y : ι → Ω → ℝ) (B : Finset ι) (C : Finset B) :
    jointCumulantOn (fun j : C ↦ Y j.1.1) =
      jointCumulantOn (fun j : C.map
        (⟨Subtype.val, Subtype.val_injective⟩ : B ↪ ι) ↦ Y j.1) := by
  calc
    _ = jointCumulantOn (fun j : C ↦
          (fun k : C.map
            (⟨Subtype.val, Subtype.val_injective⟩ : B ↪ ι) ↦ Y k.1)
            (mappedBlockElementEquiv B C j)) := by
        rfl
    _ = _ := jointCumulantOn_equiv (mappedBlockElementEquiv B C)
      (fun j ↦ Y j.1)

private theorem nested_blockCumulantProduct_eq_global
    {Ω ι : Type*} [Fintype Ω] [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (P : Finpartition (Finset.univ : Finset ι))
    (Q : ∀ B : P.parts,
      Finpartition (Finset.univ : Finset B.1)) :
    (∏ B : P.parts, ∏ C ∈ (Q B).parts,
        jointCumulantOn (fun j : C ↦ Y j.1.1)) =
      partitionCumulantProduct Y (nestedGlobalRefinement P Q) := by
  classical
  rw [partitionCumulantProduct, nestedGlobalRefinement]
  calc
    _ = ∏ B : P.parts,
        ∏ D ∈ (liftBlockPartition B.1 (Q B)).parts,
          jointCumulantOn (fun j : D ↦ Y j.1) := by
      apply Fintype.prod_congr
      intro B
      rw [liftBlockPartition_parts]
      rw [Finset.prod_image]
      · apply Finset.prod_congr rfl
        intro C _
        exact jointCumulantOn_mappedBlock Y B.1 C
      · intro C _ D _ hCD
        exact Finset.map_injective
          (⟨Subtype.val, Subtype.val_injective⟩ : B.1 ↪ ι) hCD
    _ = _ := (prod_bind_finpartition P
      (fun B : P.parts ↦ liftBlockPartition B.1 (Q B))
      (fun D ↦ jointCumulantOn (fun j : D ↦ Y j.1))).symm

noncomputable def refinementCumulantSum
    {Ω ι : Type*} [Fintype Ω] [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (P : Finpartition (Finset.univ : Finset ι)) : ℝ := by
  classical
  exact ∑ R : {R : Finpartition (Finset.univ : Finset ι) // R ≤ P},
    partitionCumulantProduct Y R.1

/-- Expanding the moment on every block of an outer partition and binding the
resulting inner partitions gives a single sum over global refinements. -/
theorem partitionMomentProduct_eq_sum_refinement_cumulant
    {Ω ι : Type*} [Fintype Ω] [Nonempty Ω]
    [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (P : Finpartition (Finset.univ : Finset ι)) :
    partitionMomentProduct Y P =
      refinementCumulantSum Y P := by
  classical
  rw [partitionMomentProduct, refinementCumulantSum]
  have hattach :
      (∏ C ∈ P.parts,
        uniformExpectation (fun ω ↦ ∏ j ∈ C, Y j ω)) =
        ∏ B : P.parts,
          uniformExpectation (fun ω ↦ ∏ j : B.1, Y j.1 ω) := by
    change (∏ C ∈ P.parts,
        uniformExpectation (fun ω ↦ ∏ j ∈ C, Y j ω)) =
      ∏ B ∈ (Finset.univ : Finset P.parts),
        uniformExpectation (fun ω ↦ ∏ j : B.1, Y j.1 ω)
    rw [Finset.univ_eq_attach]
    calc
      _ = ∏ B ∈ P.parts.attach,
          uniformExpectation (fun ω ↦ ∏ j ∈ B.1, Y j ω) :=
        (Finset.prod_attach P.parts (fun C ↦
          uniformExpectation (fun ω ↦ ∏ j ∈ C, Y j ω))).symm
      _ = _ := by
        apply Finset.prod_congr rfl
        intro B _
        apply congrArg uniformExpectation
        funext ω
        exact Finset.prod_subtype B.1 (fun _ ↦ Iff.rfl)
          (fun j ↦ Y j ω)
  rw [hattach]
  have hblock (B : P.parts) :
      uniformExpectation (fun ω ↦ ∏ j : B.1, Y j.1 ω) =
        ∑ S : Finpartition (Finset.univ : Finset B.1),
          ∏ C ∈ S.parts, jointCumulantOn (fun j : C ↦ Y j.1.1) := by
    letI : Nonempty B.1 := Finset.nonempty_coe_sort.mpr
      (P.nonempty_of_mem_parts B.2)
    exact moment_cumulant_inverse_nonempty_index (fun j : B.1 ↦ Y j.1)
  simp_rw [hblock]
  rw [Fintype.prod_sum]
  let e := nestedPartitionsEquivGlobalRefinements P
  apply Fintype.sum_equiv e
  intro Q
  exact nested_blockCumulantProduct_eq_global Y P Q

private theorem unionPartitionBlocks_injective
    {α : Type*} [DecidableEq α] {s : Finset α}
    (R : Finpartition s) :
    Function.Injective (unionPartitionBlocks R) := by
  intro G H hGH
  ext B
  rw [← block_subset_unionPartitionBlocks_iff R G B,
    ← block_subset_unionPartitionBlocks_iff R H B, hGH]

private theorem prod_blocks_eq_prod_unionPartitionBlocks
    {ι M : Type*} [Fintype ι] [DecidableEq ι] [CommMonoid M]
    (R : Finpartition (Finset.univ : Finset ι))
    (G : Finset R.parts) (f : ι → M) :
    (∏ B ∈ G, ∏ j ∈ B.1, f j) =
      ∏ j ∈ unionPartitionBlocks R G, f j := by
  classical
  rw [unionPartitionBlocks, Finset.prod_biUnion]
  intro B hB C hC hBC
  apply R.disjoint B.2 C.2
  intro h
  apply hBC
  exact Subtype.ext h

noncomputable def outerCumulantCoarseningSum
    {Ω ι : Type*} [Fintype Ω] [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι)) : ℝ :=
  ∑ S : Finpartition (Finset.univ : Finset τ.parts),
    finpartitionMobiusWeight S *
      partitionMomentProduct Y (coarsenFromBlockPartition τ S)

private theorem outer_blockMomentProduct_eq_coarsening
    {Ω ι : Type*} [Fintype Ω] [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι))
    (S : Finpartition (Finset.univ : Finset τ.parts)) :
    (∏ G ∈ S.parts,
        uniformExpectation (fun ω ↦
          ∏ B ∈ G, ∏ j ∈ B.1, Y j ω)) =
      partitionMomentProduct Y (coarsenFromBlockPartition τ S) := by
  classical
  rw [partitionMomentProduct, coarsenFromBlockPartition_parts]
  rw [Finset.prod_image (unionPartitionBlocks_injective τ).injOn]
  apply Finset.prod_congr rfl
  intro G _
  apply congrArg uniformExpectation
  funext ω
  exact prod_blocks_eq_prod_unionPartitionBlocks τ G (fun j ↦ Y j ω)

/-- The outer cumulant of the block products is the Möbius-weighted sum of
moment products over coarsenings of the prescribed block partition. -/
theorem jointCumulantOn_blockProducts_eq_outerCoarseningSum
    {Ω ι : Type*} [Fintype Ω] [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι)) :
    jointCumulantOn (fun B : τ.parts ↦
      fun ω ↦ ∏ j ∈ B.1, Y j ω) =
      outerCumulantCoarseningSum Y τ := by
  classical
  rw [jointCumulantOn, outerCumulantCoarseningSum]
  apply Finset.sum_congr rfl
  intro S _
  rw [finpartitionMobiusWeight,
    outer_blockMomentProduct_eq_coarsening]

private noncomputable def outerRefinementPairsSwap
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (τ : Finpartition (Finset.univ : Finset ι)) :
    (Σ S : Finpartition (Finset.univ : Finset τ.parts),
      {σ : Finpartition (Finset.univ : Finset ι) //
        σ ≤ coarsenFromBlockPartition τ S}) ≃
    (Σ σ : Finpartition (Finset.univ : Finset ι),
      {S : Finpartition (Finset.univ : Finset τ.parts) //
        σ ≤ coarsenFromBlockPartition τ S}) where
  toFun z := ⟨z.2.1, ⟨z.1, z.2.2⟩⟩
  invFun z := ⟨z.2.1, ⟨z.1, z.2.2⟩⟩
  left_inv := by rintro ⟨S, σ, h⟩; rfl
  right_inv := by rintro ⟨σ, S, h⟩; rfl

noncomputable def commonCoarseningMobiusSum
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) : ℝ := by
  classical
  exact ∑ S : {S : Finpartition (Finset.univ : Finset τ.parts) //
      σ ≤ coarsenFromBlockPartition τ S},
    finpartitionMobiusWeight S.1

theorem outerCumulantCoarseningSum_reindex
    {Ω ι : Type*} [Fintype Ω] [Nonempty Ω]
    [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι)) :
    outerCumulantCoarseningSum Y τ =
      ∑ σ : Finpartition (Finset.univ : Finset ι),
        commonCoarseningMobiusSum σ τ * partitionCumulantProduct Y σ := by
  classical
  rw [outerCumulantCoarseningSum]
  simp_rw [partitionMomentProduct_eq_sum_refinement_cumulant,
    refinementCumulantSum, Finset.mul_sum]
  calc
    _ = ∑ z : Σ S : Finpartition (Finset.univ : Finset τ.parts),
          {σ : Finpartition (Finset.univ : Finset ι) //
            σ ≤ coarsenFromBlockPartition τ S},
        finpartitionMobiusWeight z.1 * partitionCumulantProduct Y z.2.1 :=
      (Fintype.sum_sigma _).symm
    _ = ∑ z : Σ σ : Finpartition (Finset.univ : Finset ι),
          {S : Finpartition (Finset.univ : Finset τ.parts) //
            σ ≤ coarsenFromBlockPartition τ S},
        finpartitionMobiusWeight z.2.1 * partitionCumulantProduct Y z.1 := by
      apply Fintype.sum_equiv (outerRefinementPairsSwap τ)
      intro z
      rfl
    _ = ∑ σ : Finpartition (Finset.univ : Finset ι),
        ∑ S : {S : Finpartition (Finset.univ : Finset τ.parts) //
          σ ≤ coarsenFromBlockPartition τ S},
          finpartitionMobiusWeight S.1 * partitionCumulantProduct Y σ :=
      Fintype.sum_sigma _
    _ = _ := by
      apply Finset.sum_congr rfl
      intro σ _
      rw [commonCoarseningMobiusSum, Finset.sum_mul]

theorem left_le_productConnectivityPartition
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    σ ≤ productConnectivityPartition σ τ := by
  classical
  intro B hB
  obtain ⟨i, hiB⟩ := σ.nonempty_of_mem_parts hB
  refine ⟨(productConnectivityPartition σ τ).part i,
    (productConnectivityPartition σ τ).part_mem.mpr (Finset.mem_univ i), ?_⟩
  intro j hjB
  apply (mem_productConnectivityPartition_part_iff σ τ i j).mpr
  apply Relation.ReflTransGen.single
  left
  exact (σ.part_eq_of_mem hB hiB).trans
    (σ.part_eq_of_mem hB hjB).symm

theorem right_le_productConnectivityPartition
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    τ ≤ productConnectivityPartition σ τ := by
  classical
  intro B hB
  obtain ⟨i, hiB⟩ := τ.nonempty_of_mem_parts hB
  refine ⟨(productConnectivityPartition σ τ).part i,
    (productConnectivityPartition σ τ).part_mem.mpr (Finset.mem_univ i), ?_⟩
  intro j hjB
  apply (mem_productConnectivityPartition_part_iff σ τ i j).mpr
  apply Relation.ReflTransGen.single
  right
  exact (τ.part_eq_of_mem hB hiB).trans
    (τ.part_eq_of_mem hB hjB).symm

private theorem partition_part_eq_of_step
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {σ τ P : Finpartition (Finset.univ : Finset ι)}
    (hσP : σ ≤ P) (hτP : τ ≤ P) {i j : ι}
    (hstep : productPartitionStep σ τ i j) :
    P.part i = P.part j := by
  rcases hstep with hσ | hτ
  · obtain ⟨D, hD, hsub⟩ := hσP
      (σ.part_mem.mpr (Finset.mem_univ i))
    have hiD : i ∈ D := hsub (σ.mem_part (Finset.mem_univ i))
    have hjσ : j ∈ σ.part i := by
      rw [hσ]
      exact σ.mem_part (Finset.mem_univ j)
    have hjD : j ∈ D := hsub hjσ
    exact (P.part_eq_of_mem hD hiD).trans
      (P.part_eq_of_mem hD hjD).symm
  · obtain ⟨D, hD, hsub⟩ := hτP
      (τ.part_mem.mpr (Finset.mem_univ i))
    have hiD : i ∈ D := hsub (τ.mem_part (Finset.mem_univ i))
    have hjτ : j ∈ τ.part i := by
      rw [hτ]
      exact τ.mem_part (Finset.mem_univ j)
    have hjD : j ∈ D := hsub hjτ
    exact (P.part_eq_of_mem hD hiD).trans
      (P.part_eq_of_mem hD hjD).symm

private theorem partition_part_eq_of_productPath
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {σ τ P : Finpartition (Finset.univ : Finset ι)}
    (hσP : σ ≤ P) (hτP : τ ≤ P) {i j : ι}
    (hpath : Relation.ReflTransGen (productPartitionStep σ τ) i j) :
    P.part i = P.part j := by
  induction hpath with
  | refl => rfl
  | tail hpath hstep ih =>
      exact ih.trans (partition_part_eq_of_step hσP hτP hstep)

theorem productConnectivityPartition_le_of_common_coarsening
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {σ τ P : Finpartition (Finset.univ : Finset ι)}
    (hσP : σ ≤ P) (hτP : τ ≤ P) :
    productConnectivityPartition σ τ ≤ P := by
  classical
  intro B hB
  obtain ⟨i, hiB⟩ :=
    (productConnectivityPartition σ τ).nonempty_of_mem_parts hB
  refine ⟨P.part i, P.part_mem.mpr (Finset.mem_univ i), ?_⟩
  intro j hjB
  have hpartB : (productConnectivityPartition σ τ).part i = B :=
    (productConnectivityPartition σ τ).part_eq_of_mem hB hiB
  have hpath : Relation.ReflTransGen (productPartitionStep σ τ) i j :=
    (mem_productConnectivityPartition_part_iff σ τ i j).mp
      (hpartB.symm ▸ hjB)
  have hparts : P.part i = P.part j :=
    partition_part_eq_of_productPath hσP hτP hpath
  exact (P.mem_part_iff_part_eq_part
    (Finset.mem_univ j) (Finset.mem_univ i)).mpr hparts.symm

theorem common_coarsening_iff_connectivity_le
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι))
    (S : Finpartition (Finset.univ : Finset τ.parts)) :
    σ ≤ coarsenFromBlockPartition τ S ↔
      productConnectivityPartition σ τ ≤
        coarsenFromBlockPartition τ S := by
  constructor
  · intro hσ
    exact productConnectivityPartition_le_of_common_coarsening hσ
      (fine_le_coarsenFromBlockPartition τ S)
  · intro hK
    exact (left_le_productConnectivityPartition σ τ).trans hK

theorem card_coarsenFromBlockPartition_parts
    {α : Type*} [DecidableEq α] {s : Finset α}
    (R : Finpartition s)
    (S : Finpartition (Finset.univ : Finset R.parts)) :
    (coarsenFromBlockPartition R S).parts.card = S.parts.card := by
  classical
  rw [coarsenFromBlockPartition_parts,
    Finset.card_image_of_injective]
  exact unionPartitionBlocks_injective R

theorem card_blockPartitionOfCoarsening_parts
    {α : Type*} [DecidableEq α] {s : Finset α}
    (R : Finpartition s) (P : {P : Finpartition s // R ≤ P}) :
    (blockPartitionOfCoarsening R P).parts.card = P.1.parts.card := by
  classical
  rw [blockPartitionOfCoarsening_parts]
  apply Finset.card_image_iff.mpr
  intro D hD E hE hDE
  have h := congrArg (unionPartitionBlocks R) hDE
  simpa only [union_fineBlocksInOuter_eq P.2 hD,
    union_fineBlocksInOuter_eq P.2 hE] using h

private noncomputable def
    admissibleOuterPartitionsEquivConnectivityBlockPartitions
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    {S : Finpartition (Finset.univ : Finset τ.parts) //
      σ ≤ coarsenFromBlockPartition τ S} ≃
    Finpartition (Finset.univ : Finset
      (productConnectivityPartition σ τ).parts) where
  toFun S :=
    blockPartitionOfCoarsening (productConnectivityPartition σ τ)
      ⟨coarsenFromBlockPartition τ S.1,
        (common_coarsening_iff_connectivity_le σ τ S.1).mp S.2⟩
  invFun T :=
    ⟨blockPartitionOfCoarsening τ
        ⟨coarsenFromBlockPartition (productConnectivityPartition σ τ) T,
          (right_le_productConnectivityPartition σ τ).trans
            (fine_le_coarsenFromBlockPartition
              (productConnectivityPartition σ τ) T)⟩,
      by
        rw [common_coarsening_iff_connectivity_le]
        rw [coarsenFromBlockPartition_blockPartitionOfCoarsening]
        exact fine_le_coarsenFromBlockPartition
          (productConnectivityPartition σ τ) T⟩
  left_inv S := by
    let K := productConnectivityPartition σ τ
    let PK : {P : Finpartition (Finset.univ : Finset ι) // K ≤ P} :=
      ⟨coarsenFromBlockPartition τ S.1,
        (common_coarsening_iff_connectivity_le σ τ S.1).mp S.2⟩
    let PT : {P : Finpartition (Finset.univ : Finset ι) // τ ≤ P} :=
      ⟨coarsenFromBlockPartition K (blockPartitionOfCoarsening K PK),
        (right_le_productConnectivityPartition σ τ).trans
          (fine_le_coarsenFromBlockPartition K
            (blockPartitionOfCoarsening K PK))⟩
    let PS : {P : Finpartition (Finset.univ : Finset ι) // τ ≤ P} :=
      ⟨coarsenFromBlockPartition τ S.1,
        fine_le_coarsenFromBlockPartition τ S.1⟩
    have hPTPS : PT = PS := by
      apply Subtype.ext
      exact coarsenFromBlockPartition_blockPartitionOfCoarsening K PK
    apply Subtype.ext
    change blockPartitionOfCoarsening τ PT = S.1
    rw [hPTPS]
    exact blockPartitionOfCoarsening_coarsenFromBlockPartition τ S.1
  right_inv T := by
    let K := productConnectivityPartition σ τ
    let Pτ : {P : Finpartition (Finset.univ : Finset ι) // τ ≤ P} :=
      ⟨coarsenFromBlockPartition K T,
        (right_le_productConnectivityPartition σ τ).trans
          (fine_le_coarsenFromBlockPartition K T)⟩
    let PKafter : {P : Finpartition (Finset.univ : Finset ι) // K ≤ P} :=
      ⟨coarsenFromBlockPartition τ (blockPartitionOfCoarsening τ Pτ),
        (common_coarsening_iff_connectivity_le σ τ
          (blockPartitionOfCoarsening τ Pτ)).mp (by
            change σ ≤ coarsenFromBlockPartition τ
              (blockPartitionOfCoarsening τ Pτ)
            rw [coarsenFromBlockPartition_blockPartitionOfCoarsening]
            exact (left_le_productConnectivityPartition σ τ).trans
              (fine_le_coarsenFromBlockPartition K T))⟩
    let PK : {P : Finpartition (Finset.univ : Finset ι) // K ≤ P} :=
      ⟨coarsenFromBlockPartition K T,
        fine_le_coarsenFromBlockPartition K T⟩
    have hPK : PKafter = PK := by
      apply Subtype.ext
      exact coarsenFromBlockPartition_blockPartitionOfCoarsening τ Pτ
    change blockPartitionOfCoarsening K PKafter = T
    rw [hPK]
    exact blockPartitionOfCoarsening_coarsenFromBlockPartition
      K T

private theorem admissibleOuterPartitions_weight_preserved
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι))
    (S : {S : Finpartition (Finset.univ : Finset τ.parts) //
      σ ≤ coarsenFromBlockPartition τ S}) :
    finpartitionMobiusWeight S.1 =
      finpartitionMobiusWeight
        (admissibleOuterPartitionsEquivConnectivityBlockPartitions σ τ S) := by
  let K := productConnectivityPartition σ τ
  let PK : {P : Finpartition (Finset.univ : Finset ι) // K ≤ P} :=
    ⟨coarsenFromBlockPartition τ S.1,
      (common_coarsening_iff_connectivity_le σ τ S.1).mp S.2⟩
  have houter := card_blockPartitionOfCoarsening_parts K PK
  have hinner := card_coarsenFromBlockPartition_parts τ S.1
  have hcard :
      (admissibleOuterPartitionsEquivConnectivityBlockPartitions σ τ S).parts.card =
        S.1.parts.card := houter.trans hinner
  rw [finpartitionMobiusWeight, finpartitionMobiusWeight, hcard]

private theorem finpartition_univ_subsingleton_of_isEmpty
    {α : Type*} [Fintype α] [DecidableEq α] [IsEmpty α] :
    Subsingleton (Finpartition (Finset.univ : Finset α)) := by
  constructor
  intro P Q
  apply Finpartition.ext
  have huniv : (Finset.univ : Finset α) = ∅ := by simp
  have hP : P.parts = ∅ := Finpartition.parts_eq_empty_iff.mpr huniv
  have hQ : Q.parts = ∅ := Finpartition.parts_eq_empty_iff.mpr huniv
  rw [hP, hQ]

private theorem sum_finpartitionMobiusWeight_empty
    {α : Type*} [Fintype α] [DecidableEq α] [IsEmpty α] :
    (∑ P : Finpartition (Finset.univ : Finset α),
      finpartitionMobiusWeight P) = 1 := by
  classical
  letI : Subsingleton (Finpartition (Finset.univ : Finset α)) :=
    finpartition_univ_subsingleton_of_isEmpty
  have huniv : (Finset.univ : Finset α) = ∅ := by simp
  let P0 : Finpartition (Finset.univ : Finset α) :=
    (Finpartition.empty (Finset α)).copy huniv.symm
  rw [Fintype.sum_subsingleton _ P0]
  have hparts : P0.parts = ∅ :=
    Finpartition.parts_eq_empty_iff.mpr huniv
  simp [finpartitionMobiusWeight, hparts]

private theorem sum_finpartitionMobiusWeight_all
    {α : Type*} [Fintype α] [DecidableEq α] :
    (∑ P : Finpartition (Finset.univ : Finset α),
      finpartitionMobiusWeight P) =
      if Fintype.card α ≤ 1 then 1 else 0 := by
  classical
  rcases isEmpty_or_nonempty α with hα | hα
  · letI : IsEmpty α := hα
    rw [sum_finpartitionMobiusWeight_empty]
    simp [Fintype.card_eq_zero]
  · letI : Nonempty α := hα
    rw [sum_finpartitionMobiusWeight]
    have hpos : 0 < Fintype.card α := Fintype.card_pos
    by_cases hone : Fintype.card α = 1
    · simp [hone]
    · have hgt : 1 < Fintype.card α := by omega
      simp [hone, show ¬Fintype.card α ≤ 1 by omega]

theorem commonCoarseningMobiusSum_eq_connectivity_le_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    commonCoarseningMobiusSum σ τ =
      if (productConnectivityPartition σ τ).parts.card ≤ 1 then 1 else 0 := by
  classical
  rw [commonCoarseningMobiusSum]
  let K := productConnectivityPartition σ τ
  calc
    _ = ∑ T : Finpartition (Finset.univ : Finset K.parts),
        finpartitionMobiusWeight T :=
      Fintype.sum_equiv
        (admissibleOuterPartitionsEquivConnectivityBlockPartitions σ τ)
        (fun S ↦ finpartitionMobiusWeight S.1)
        finpartitionMobiusWeight
        (admissibleOuterPartitions_weight_preserved σ τ)
    _ = if Fintype.card K.parts ≤ 1 then 1 else 0 :=
      sum_finpartitionMobiusWeight_all
    _ = _ := by rw [Fintype.card_coe]

theorem commonCoarseningMobiusSum_eq_connectivity
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    commonCoarseningMobiusSum σ τ =
      if (productConnectivityPartition σ τ).parts.card = 1 then 1 else 0 := by
  classical
  rw [commonCoarseningMobiusSum]
  let K := productConnectivityPartition σ τ
  letI : Nonempty K.parts := Finset.nonempty_coe_sort.mpr
    (K.parts_nonempty Finset.univ_nonempty.ne_empty)
  calc
    _ = ∑ T : Finpartition (Finset.univ : Finset K.parts),
        finpartitionMobiusWeight T :=
      Fintype.sum_equiv
        (admissibleOuterPartitionsEquivConnectivityBlockPartitions σ τ)
        (fun S ↦ finpartitionMobiusWeight S.1)
        finpartitionMobiusWeight
        (admissibleOuterPartitions_weight_preserved σ τ)
    _ = if Fintype.card K.parts = 1 then 1 else 0 :=
      sum_finpartitionMobiusWeight
    _ = if K.parts.card = 1 then 1 else 0 := by
      rw [Fintype.card_coe]
    _ = _ := rfl

theorem productPartitionConnected_iff_connectivity_card_le_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (σ τ : Finpartition (Finset.univ : Finset ι)) :
    ProductPartitionConnected σ τ ↔
      (productConnectivityPartition σ τ).parts.card ≤ 1 := by
  classical
  rcases isEmpty_or_nonempty ι with hι | hι
  · letI : IsEmpty ι := hι
    have huniv : (Finset.univ : Finset ι) = ∅ := by simp
    have hparts : (productConnectivityPartition σ τ).parts = ∅ :=
      Finpartition.parts_eq_empty_iff.mpr huniv
    constructor
    · intro _
      simp [hparts]
    · intro _ i
      exact isEmptyElim i
  · letI : Nonempty ι := hι
    rw [productPartitionConnected_iff_connectivity_card_one]
    have hpos : 0 < (productConnectivityPartition σ τ).parts.card :=
      Finset.card_pos.mpr
        ((productConnectivityPartition σ τ).parts_nonempty
          Finset.univ_nonempty.ne_empty)
    omega

/- The exact connected product-cumulant identity, including the empty finite
index endpoint. -/
theorem product_cumulant_connected_identity
    {Ω ι : Type*} [Fintype Ω] [Nonempty Ω]
    [Fintype ι] [DecidableEq ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι)) :
    jointCumulantOn (fun B : τ.parts ↦
      fun ω ↦ ∏ j ∈ B.1, Y j ω) =
      connectedPartitionCumulantSum Y τ := by
  classical
  rw [jointCumulantOn_blockProducts_eq_outerCoarseningSum,
    outerCumulantCoarseningSum_reindex,
    connectedPartitionCumulantSum]
  apply Finset.sum_congr rfl
  intro σ _
  rw [commonCoarseningMobiusSum_eq_connectivity_le_one]
  by_cases hconn : ProductPartitionConnected σ τ
  · have hcard :=
      (productPartitionConnected_iff_connectivity_card_le_one σ τ).mp hconn
    simp [hconn, hcard]
  · have hcard : ¬(productConnectivityPartition σ τ).parts.card ≤ 1 :=
      fun hc ↦ hconn
        ((productPartitionConnected_iff_connectivity_card_le_one σ τ).mpr hc)
    simp [hconn, hcard]

theorem product_cumulant_connected_identity_nonempty
    {Ω ι : Type*} [Fintype Ω] [Nonempty Ω]
    [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (Y : ι → Ω → ℝ)
    (τ : Finpartition (Finset.univ : Finset ι)) :
    jointCumulantOn (fun B : τ.parts ↦
      fun ω ↦ ∏ j ∈ B.1, Y j ω) =
      connectedPartitionCumulantSum Y τ := by
  classical
  rw [jointCumulantOn_blockProducts_eq_outerCoarseningSum,
    outerCumulantCoarseningSum_reindex,
    connectedPartitionCumulantSum]
  apply Finset.sum_congr rfl
  intro σ _
  rw [commonCoarseningMobiusSum_eq_connectivity]
  by_cases hconn : ProductPartitionConnected σ τ
  · have hcard :=
      (productPartitionConnected_iff_connectivity_card_one σ τ).mp hconn
    simp [hconn, hcard]
  · have hcard : (productConnectivityPartition σ τ).parts.card ≠ 1 :=
      fun hc ↦ hconn
        ((productPartitionConnected_iff_connectivity_card_one σ τ).mpr hc)
    simp [hconn, hcard]

/-- Both conjuncts of the exact frozen I09 interface. -/
theorem product_cumulant_connected_partition_identity (b : ℕ) :
    (∑ j ∈ Finset.Icc 1 b,
      (Nat.stirlingSecond b j : ℤ) * (-1 : ℤ) ^ (j - 1) *
        (Nat.factorial (j - 1) : ℤ)) =
      (if b = 1 then 1 else 0) ∧
    ∀ {Ω ι : Type*} [Fintype Ω] [Nonempty Ω]
      [Fintype ι] [DecidableEq ι]
      (Y : ι → Ω → ℝ)
      (τ : Finpartition (Finset.univ : Finset ι)),
      jointCumulantOn (fun B : τ.parts ↦
        fun ω ↦ ∏ j ∈ B.1, Y j ω) =
      connectedPartitionCumulantSum Y τ := by
  exact ⟨stirling_product_cumulant_coefficient b,
    fun Y τ ↦ product_cumulant_connected_identity Y τ⟩

end Problem56
