from pathlib import Path
import json,hashlib
E=Path(__file__).resolve().parents[2]; W=E.parents[3]
candidates=json.loads((E/'reviews/reverse_pass2/blinded_pass1_candidates.json').read_text())['candidates']
loc=['124-139','443-639','1656-1710;2417-2709','716-776','849-1064','938-969','930-936;1041-1064','1194-1321','1323-1353','1399-1620','1814-2133','2306-2399','2417-2593','2739-2873','2899-3002']
objects=['Width C,k precedes fixed V; SquaredNormEdges becomes the manuscript z norm by frame_isometry.','Actual compressed spectrum, interior 2x2 blocks, endpoint singleton blocks and complex roots.','Exact selector/equality and entry partitions; absolute expected signed trace.','Same signed expectation and compensated pointwise event, not expected absolute trace.','Correct target-row/source-column transpose bridge and two genuine r-dimensional boundaries; zero-dimensional identity issue remains.','Finite fixed-boundary sums, arbitrary selected copies, identity labels enforce equality; external Definition13 forest clause is not encoded.','General graph data with deletion-connectedness, indexed loops and parallel edges; new conversion assumes no parity.','Real integral moment data on arbitrary probability sample spaces and occurrence positions.','FiniteJointMoments, independent random vectors, real constants, and IdentDistrib symmetry.','Same fixed V, two independent Rademacher layers, normalized inner Walsh factors.','Concrete equality partitions of numbered cyclic positions; ports retain opposite mates and returning endpoints.','Actual F2 matrix rows and binary-vector labels; kernel cardinality versus injective subset.','Exact AggregateEntryPartition Q d h and product c(rho); absolute values inside both sums.','Arbitrary measurable random frame law independent of each finite sampling noise; Eminus/Eplus need not be independent.','Uniform k-subsets without replacement; random frame from the exact two sign layers.']
deletions=['Removing the simultaneous-vector interpretation leaves a weaker application statement; present client supplies both directions.','Deleting endpoints or nonreal compensation invalidates the transfer; both are explicit.','Deleting weighted partition aggregation loses the load-bearing trace bound; actual code reaches it.','Without signed compensation, Markov cannot be applied to the unshifted trace; C includes compensation.','Dropping the identity-norm-one sentence preserves the named graph norm bound; its unconditional source scope still needs clarification.','Dropping fixed-boundary preservation loses the operator comparison; finite-sum equality supplies it.','Deleting the new general conversion leaves only a narrower even-degree statement; new topology construction closes the broader obligation.','Without finite partition inversion/product regrouping the general lemma is not established; actual integral code provides both.','Removing independence/multilinearity/shift/symmetry clauses would weaken the named lemma; all six components are present.','Without law-preserving modulation the XOR vanishing lacks justification; exact diagonal transforms establish it.','Without an actual decoder, code cardinality alone is insufficient; canonical dynamics recovers the original equality partition.','Without exact rank-nullity count the n^(v-h) factor is unsupported; actual count is separate from injectivity.','Deleting the dimension transport or actual sum would leave a surrogate estimate; both are explicit.','Without the joint-law bridge an averaged pointwise statement would not establish actual joint failure; finiteNoiseFailureLaw supplies it.','Replacing fixed-size inclusion probabilities by iid ones would change the exact finite-population identity; actual code preserves them.']
endpoints=['Full sampling and nonempty subset spaces; fixed frame before randomness.','lambda=0,1; E=0,I; repeated/defective roots; at most r paired blocks.','Empty partition classes and natural subtraction handled before extracting feasible dimensions.','p>=2 from the logarithmic rank regime, theta positive, signed lower compensation.','N=0 makes ||I_0||=0. C does not explicitly exclude it, although rank r>=1 and n=2^m application dimensions are positive.','Even zero-dimensional finite sums are preserved; exact norm equality needs its separate boundary analysis.','Closed ears and one-edge loops allowed before split; distinct original boundaries preserved.','Nonempty argument set and empty moment normalization; repeated variables occupy distinct positions.','Order>=2 for shifts; odd order for symmetric repeated variable; integrability of finite products only.','q=1 mean; repetitions of entry indices; XOR is necessary only.','s+t=0 separate branch, p=2 four parallel edges, returning and parallel links, loop half-edges distinct.','m=0, rank at most vertex count, repeated/zero rows; injectivity can yield an empty subset.','Empty classes, d<=p-1 and s+h<=p when nonempty; theta,r,n positive in inverse factors.','Threshold endpoints, ties almost surely absent, k<=n, densities<=1, arbitrary continuous frame distributions.','n=1 and k=n exact; diagonal all-equal fourth-moment term subtracted twice.']
entries=[]
for i,c in enumerate(candidates):
 e=dict(c); e.update({'MANUSCRIPT_STEP':'Frozen C main.tex:'+loc[i],'DELETION_TEST':deletions[i],'OBJECT_IDENTITY_TEST':objects[i],'PROOF_ROUTE_SUBSTITUTION_TEST':'SHARED_MATHEMATICAL_SCOPE_WITH_VALID_ALTERNATIVE_PROOF' if i in [4,5,6,7,8,10,13] else 'SHARED_MATHEMATICAL_ROUTE','BOUNDARY_ENDPOINT_TEST':endpoints[i],'CLASSIFICATION':'RA3' if i==4 else 'RA0','RECOMMENDATION':'Clarify positive coordinate dimensions or weaken generic identity-norm/product wording; preserve frozen bytes and rebind any actual correction.' if i==4 else 'No necessary manuscript correction for this obligation. See source-first report for proof-route distinctions.'});entries.append(e)
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
files=['inventory_named_results.json','inventory_interfaces.json','inventory_definitions.json','source_A_manifest.json','baseline_B_manifest.json','frozen_C_manifest.json','snapshots/solution.tex','snapshots/research/problem_5_6/paper/v6/main.tex']
r={'schema':'independent_source_first_reverse_pass2_local_report_v1','KERNEL_OPERATION':'PROOF_PORT_AUDIT','AUTHORITY_MODE':'AUDIT_ONLY','OPERATION_STATUS':'REPAIR','VERIFIER_VERDICT':None,'REVERSE_AUDIT_STATUS':'REPAIR','AUDITOR_CONTEXT':'/root/reverse_pass2','FROZEN_V6_COMMIT':'4551d08f3732a3ca06c2f576794e1d75790e1972','RECOMMENDATIONS_VISIBLE':'NO','source_first_completed_before_blinded_ids':True,'runtime_invocation_receipt':'UNAVAILABLE: authenticating controller runtime receipt not exposed; no fabricated receipt','formal_v2_schema_status':'NOT_CLAIMED: local report preserves real independent review; authenticated runtime receipt and strict parent lifecycle bindings are separate','inventory_counts':{'named':12,'interfaces':50,'definitions':34},'FINAL_ENTRIES':entries,'source_hashes':{f:sha(E/f) for f in files},'implementation_binding':'PENDING_FINAL_REGENERATION','required_manuscript_repairs':[{'id':'I-V6-11-ZERO-DIMENSION','classification':'RA3','locators':['main.tex:849-872','main.tex:958-969'],'issue':'No explicit positive N_u convention establishes unconditional identity norm one; I_0 has norm zero. Generic isolated-zero-vertex split also changes norm product from one to zero.','effect':'Blocks unconditional native literal scope for I-V6-11; no counterexample to named rank-r graph bound or main OSE conclusion.','minimal_options':['State N_u positive integers in graph definition.','Use identity norm at most one and nonincreasing norm product, adding equality for positive dimensions.']}],'additional_bridge_found_and_reviewed':{'interface':'I-V6-03','expected_approval':'reviews/reverse_pass2/trace_and_centering_expected_review.json','actual_source':'Problem56/PaperV6/TracePower.lean','semantic_review':'PASS: exact rectangular trace-power induction and theta-inverse Gram centering; final graph binding pending'},'source_reading_limitations':['No rendered PDF or diagram inspection by this reviewer; no visual correctness claim.','No independent Lean execution, cold build, kernel replay or export test by this reviewer.','Not every source prose sentence is claimed to have a separate Lean theorem.']}
(E/'reviews/independent_reverse_pass2.json').write_text(json.dumps(r,indent=2)+'\n')
print(len(entries),r['REVERSE_AUDIT_STATUS'])
